language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t andrwcao/frontend-app -f Dockerfile.dev .
script:
  - docker run -e CI=true andrwcao/frontend-app npm run test
deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker-travis-AWS'
  env: 'Dockertravisaws-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-982548795241'
  bucket_path: 'docker-travis-AWS'
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
